import { SiSwiggy } from "react-icons/si"
import { NavLink } from "react-router-dom"

const TermsandConditions = ()=>{return(<>
    <div className="shadow-md w-full sticky top-0 bg-white p-6">
        <div className="max-w-[1200px] mx-auto">
            <NavLink to='/'><SiSwiggy
                className="text-4xl inline text-[#f38217]"
            /></NavLink>
            <h1 className="inline ml-10 font-bold tracking-tighter text-zinc-600 text-l">TERMS AND CONDITIONS</h1> 
        </div>
    </div>
    <div className="max-w-[1200px] mx-auto my-6">
    <h3 className="font-bold my-4 tracking-tighter text-lg">1. Terms of Use</h3>
    <p>Welcome to our Swiggy app clone, a platform connecting customers with a wide range of restaurants and food delivery services. By accessing or using our app, you agree to be bound by these Terms of Use, which constitute a legal agreement between you and [FoodieDelivery]. If you do not agree with these terms, you must refrain from using the app. We reserve the right to modify these terms at any time, and such changes will be effective immediately upon posting. It is your responsibility to review these terms regularly to ensure you are aware of any changes.</p><br/>
    <p>Our app is committed to providing an efficient and reliable service. However, we do not guarantee the availability of any restaurant or menu item and are not responsible for any errors or omissions in the service provided by third-party partners. Orders placed through our app are subject to the availability of the menu items at the time of order and may be subject to changes or cancellations by the restaurant. Prices and availability of menu items are subject to change without notice. Swiggy clone is not liable for any delay or failure in delivery due to circumstances beyond our control.</p><br/>
    <p>By using Swiggy clone, you agree to provide accurate and complete information when creating an account and placing an order. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must be at least 18 years of age to create an account and use the service. Swiggy clone reserves the right to suspend or terminate your account if any suspicious or fraudulent activity is detected. Additionally, you agree not to use the app for any unlawful or prohibited activities. Violations of these terms may result in the termination of your access to the app and potential legal action.</p>
    <p>By using Swiggy clone, you agree to provide accurate and complete information when creating an account and placing an order. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must be at least 18 years of age to create an account and use the service. Swiggy clone reserves the right to suspend or terminate your account if any suspicious or fraudulent activity is detected. Additionally, you agree not to use the app for any unlawful or prohibited activities. Violations of these terms may result in the termination of your access to the app and potential legal action</p><br/>
    <p>By using Swiggy clone, you agree to provide accurate and complete information when creating an account and placing an order. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must be at least 18 years of age to create an account and use the service. Swiggy clone reserves the right to suspend or terminate your account if any suspicious or fraudulent activity is detected. Additionally, you agree not to use the app for any unlawful or prohibited activities. Violations of these terms may result in the termination of your access to the app and potential legal action</p><br/>
    <p>By using Swiggy clone, you agree to provide accurate and complete information when creating an account and placing an order. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must be at least 18 years of age to create an account and use the service. Swiggy clone reserves the right to suspend or terminate your account if any suspicious or fraudulent activity is detected. Additionally, you agree not to use the app for any unlawful or prohibited activities. Violations of these terms may result in the termination of your access to the app and potential legal action</p><br/>
    <p>By using Swiggy clone, you agree to provide accurate and complete information when creating an account and placing an order. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must be at least 18 years of age to create an account and use the service. Swiggy clone reserves the right to suspend or terminate your account if any suspicious or fraudulent activity is detected. Additionally, you agree not to use the app for any unlawful or prohibited activities. Violations of these terms may result in the termination of your access to the app and potential legal action</p><br/>

    </div>
</>)}
export default TermsandConditions